language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"
before_script:
- cd StyleFrame/tests/
- chmod +x style_frame_tests.py
- pwd
script: python style_frame_tests.py
